### ISSUE TITLE
Pages with Parameters should be (optionally) combined

### ISSUE THREAD

**Issue by MatthK** [electerious/Ackee#113]
I have a website with pages that have parameters.

rm.asp?W=XXX&C=123

Is there a way to ignore the parameters and see how many rm.asp page views there are?

**Comment by electerious** [comment]
It's not possible right now. Some sites are using parameters for navigation, so we can't remove them by default. I guess that we need an option for that.

**Comment by lucasdcrk** [comment]
@electerious Would be cool to have a way to accomplish this when using parameter segments

![46yn.png](https://i.apo.pm/s/46yn.png)

Server or client-wide, perhaps something in the tracker to override some urls (in my case replacing /servers/* by /servers).

**Comment by electerious** [comment]
Turns out that it's already possible to change the URL 😊

1. Get [default attributes](https://github.com/electerious/ackee-tracker#attributes)

```
const attributes = ackeeTracker.attributes()
// or
const attributes = ackeeTracker.attributes(true)
```

2. Adjust the attributes

Ackee uses `window.location.href` for the `siteLocation`. You can simply replace this value and provide a custom URL. This allows you to remove unnecessary parameters. You can also transform a state-based navigation into a readable URL.

```
const customAttributes = {
	...attributes,
	siteLocation: removeParameters(window.location.href),
}
```

3. Create a instance and track the visit

```
const instance = ackeeTracker.create({
	server: 'https://example.com',
	domainId: 'hd11f820-68a1-11e6-8047-79c0c2d9bce0'
})

instance.record(customAttributes)
```

**Comment by MatthK** [comment]
How would I implement that into the one-line script? Would the following work?

data-ackee-opts='{ "siteLocation": removeParameters(window.location.href) }'

Or is this too easy?

**Comment by electerious** [comment]
@MatthK It's currently not possible with the one-line script. It only works when using `ackee-tracker` as a module.

**Comment by electerious** [comment]
I've created a new issue. Would be cool if someone could write a documentation on how to modify URLs: https://github.com/electerious/Ackee/issues/163
