### ISSUE TITLE
Plans to transition away from MongoDB

### ISSUE THREAD

**Issue by SebDanielsson** [electerious/Ackee#118]
Are there any plans for transitioning away from MongoDB not after their change of license? For example to SQLite or MariaDB?

**Comment by electerious** [comment]
There're no plans to switch away from MongoDB. What's up with their license?

**Comment by SebDanielsson** [comment]
Most distros have dropped it from their official repositories.

From ArchLinux mailing list:
"... there is a discussion regarding mongodb
and the relicense from AGPLv3 to SSPLv1. RedHat has dropped it from their
repository[1], and Debian is assumed to follow suit[2]. This is mostly due SSPL
not being considered a free-license. It is currently being reviewed by OSI for
inclusion, but it is not looking bright currently[3]. The OSI discussion is for
SSPLv2, but it's my understanding that they are essentially the same license
with some fixups.

Obviously, we don't care about the license being free nor OSI compliant. We only
care if we are allowed to redistribute or not."

https://web.archive.org/web/20190804225351/https://lists.archlinux.org/pipermail/arch-dev-public/2019-January/029430.html

**Comment by electerious** [comment]
I don't think this is relevant for Ackee as we don't redistribute MongoDB. It's not part of Ackee. Thanks for letting me know anyway!

**Comment by donmccurdy** [comment]
It would be a big positive step (from my perspective, at least!) if Ackee could use a GraphQL API to its database. This would allow anyone to keep using MongoDB if they want (see https://docs.mongodb.com/realm/graphql/) but would let other users self-host some other type of GraphQL-compatible database if they prefer. In my case, self-hosting MongoDB is [not cost-effective for hobby projects with higher traffic](https://github.com/electerious/Ackee/issues/120), but other databases that implement GraphQL like https://fauna.com/ would be free.

Disclaimer: I'm not actually very familiar with GraphQL, but this seems to be a premise of its design.

**Comment by electerious** [comment]
It's planned to switch to a GraphQL API, but this would only allow the client or other clients to communicate with the Ackee back-end. If you want a to use a different database you also need to replace the back-end with a custom one that implement the same GraphQL schema. A GraphQL database won't help because the Ackee backend isn't just a database. If we want to support GraphQL databases then Ackee needs to implement them (back-end <- GraphQL -> database). This would be equal to supporting multiple databases which isn't planned.
