### ISSUE TITLE
Critical: Realtime Live Traffic Overview, Behavior Flow and Conversion Goals Feature Update, Also Custom Date Range Function

### ISSUE THREAD

**Issue by ux4web** [electerious/Ackee#128]
It is very important for a tracking system to have realtime live traffic view panel, behavior flow, and conversions goal settings so that proper UX can be measured. Please add these features in the next update as without these everything else is perfect, smooth with all those buttery interactions and cool UI but these features are really critical and must go on the system.

**Comment by lucasdcrk** [comment]
I don't think this the direction @electerious want this project to go, also this is definitely not the way to ask.

**Comment by ux4web** [comment]
> I don't think this the direction @electerious want this project to go, also this is definitely not the way to ask.

Definitely then let's see what @electerious replies. Since they had no support channel like Slack or something else, so I raised my query here.

**Comment by electerious** [comment]
Like @lucasdcrk says. It's not critical and it's definitely not something I **must** add to Ackee.

**Live traffic view**
The next major version will show the number of visitors currently on your site. It's a feature I'm currently working on.

**Behaviour flow**
That's not possible because Ackee doesn't track the browsing history of users. It focuses on privacy and can't build a behaviour flow.

**Conversions goal settings **
That's still planned, but still requires some time (https://github.com/electerious/Ackee/issues/40). The next version focuses on the dashboard and API.
