### ISSUE TITLE
0 page views unless in yearly mode.

### ISSUE THREAD

**Issue by origamiman72** [electerious/Ackee#138]
Hi!
I set up ackee on my website and tested it by visiting it, but the page views don't show on the views/durations page unless I'm in Yearly mode (or detailed mode in the duration page). Otherwise it just displays 0 views / 0 seconds for duration. Ackee is logging the views since they display in the yearly view, the pages page, and in referrals, but in all other pages they don't seem to exist.

**Comment by electerious** [comment]
It might happen that a view shows up on the wrong day because of [a bug](https://github.com/electerious/Ackee/issues/88), but it's unlikely that this shift is that significant.

Is it possible that the date/time of your server is incorrect?

You can also switch to pages mode and show the latest entries. When you hover over an entry it shows you when this entry has been added. It would be interesting to know if date is correct.

**Comment by electerious** [comment]
Will close the issue for now as I need more information.
