### ISSUE TITLE
Serverless functions and Ackee

### ISSUE THREAD

**Issue by Go-Merk** [electerious/Ackee#155]
Is it possible to deploy and use Ackee in [Vercel](https://vercel.com)? One of the supported languages is [Node.JS](https://vercel.com/docs/serverless-functions/supported-languages#node.js) for serveless functions, I'm taking the example of [Umami](https://umami.is), also an open source analytics software which claims being able to run on vercel and netlify, interesting enough, both platforms for static aplications. 

**The question:** is it technically possible for Ackee to do the same? I'm guessing, query the database using a serveless funtion.

I think it would be a huge step for Ackee, as this would make it a lot more acessible, anyone made an attempt on this? 🤔

**Comment by electerious** [comment]
I‘ve experimented a bit with serverless functions and it should be very easy to make Ackee ready for Vervel and Netlify.

We could build all static files and make them available in a /build folder (index.html, index.js, index.css, favicon.js and tracker.js). The routes are already available, we just need to add a script that runs the functions and saves the output.

The only serverless function we need is for the GraphQL requests. apollo-server-lambda should do the job.

**Comment by Go-Merk** [comment]
Awesome!!! This is really good news, 😄👌. That would make Ackee less dependent of server-side hosting like Heroku, it would open many possibilities.

**Comment by electerious** [comment]
I've created an experiment, but it still needs some work: https://github.com/electerious/Ackee/tree/feature/serverless

1) I've added a `build` command that builds all static files into `build`
2) There's a Netlify config in the root of the project which still misses some environment variables
3) An `api.js` function in located inside `functions`. `isAuthenticated` can't handle the lambda request and needs to be adjusted (mainly because of the `permit` module). There's also a strange workaround in `src/types/index.js`. It seems that serverless functions can't load files that resolve using `__dirname`. Not sure why, but inlining all the GraphQL files works.
4) The database connection part is currently missing.

Would be great if someone could help to push this forward :)

**Comment by electerious** [comment]
I've managed to get Ackee up and running on Netlify 🎉

The [serverless branch](https://github.com/electerious/Ackee/tree/feature/serverless) contains everything you need. Just add the following three environment variables and you're ready!

The first request is a bit slow, but it get's faster soon. Would be interesting to know if we can boost the performance even more.

![environment](https://user-images.githubusercontent.com/499088/94344057-fab23780-001c-11eb-80f8-6a2f6cbeeedf.png)

**Comment by electerious** [comment]
Here's a step-by-step guide: https://github.com/electerious/Ackee/blob/feature/serverless/docs/Get%20started.md#with-netlify

**Comment by electerious** [comment]
The serverless branch has been merged into develop. It will be part of the next release. Please note that the first request is a bit slow, but it get's faster soon. Would be interesting to know if we can boost the performance even more. Feedback is still welcome.

**Comment by Burnsy** [comment]
Hi, i just tried to push this to vercel and it looks like it gives an error due to the package.json node engine.

![image](https://user-images.githubusercontent.com/15834048/97300597-95857800-184e-11eb-8405-3777eaa75357.png)

any thoughts on how to get this deployed on vercel? 

Thanks!
