### ISSUE TITLE
Automatically add domain to list of allowed origins (CORS)

### ISSUE THREAD

**Issue by BetaHuhn** [electerious/Ackee#159]
It would be awesome if Ackee would automatically add a newly created domain to the list of allowed origins, instead of manually having to ssh into my server and add the domain to the env variable "ACKEE_ALLOW_ORIGIN". 

This behavior could be turned on by setting "ACKEE_ALLOW_ORIGIN" to "auto" (or something similar). If it is not set to auto, Ackee could just use the values provided, as it currently does.

What do you think @electerious ? I would be interested in making a PR for this, if it is wanted.

**Comment by electerious** [comment]
There's currently no relation between a domain and URL (we don't ask for a URL when you create a domain). That's mainly because you can also create a domain for an app.

The ACKEE_ALLOW_ORIGIN option is very basic and shouldn't exist at all. It's recommended to use a reverse proxy instead, because Ackee shouldn't reinvent the wheel when it comes to hosting/server setup. I therefore don't want to make this option any smarter. It exists because some services handle SSL for you, but don't allow to set custom CORS headers.

**Comment by BetaHuhn** [comment]
Okay, makes sense👍
