### ISSUE TITLE
Access tokens that don't expire specifically for API integrations

### ISSUE THREAD

**Issue by BetaHuhn** [electerious/Ackee#176]
I recently created a CLI tool called [ackee-report](https://github.com/BetaHuhn/ackee-report) which lets you create monthly performance reports of your Ackee data and send them via email  (also solves #59).

Right now you have to specify your Ackee username and password as the program has to login and create a new token each time it runs. Even though the token is renewed after each use, it doesn't solve the issue as the program is not intended to run daily and the token expires after the TTL has passed. The only way to solve this would be to set the TTL extremely long, which is not an ideal solution.

It would be better if you can create a token specifically for API integrations inside the Ackee UI. Those tokens wouldn't expire until you manually revoke them. There could also be an option to make them read only, but this isn't as relevant.

As Ackee gets more users and more tools built on Ackee emerge, I think this is something which is needed to make integrations/tools more secure and easier to build and setup.

**Comment by electerious** [comment]
💯

I've almost started to work on this feature last week, because I also need it for the [menu bar app](https://twitter.com/getackee/status/1301883503127265283) and my [iOS widget](https://twitter.com/getackee/status/1320996848623099909).

Here's what it needs:

- Two new fields in the database for tokens
  - `permanent` must be Boolean. Default: `false`
  - `title` must be String
- Skip the TTL validation when it's a permanent token
- A way to add permanent tokes via the API (https://github.com/electerious/Ackee/blob/master/src/types/tokens.js#L21 => `title: String` and `permanent: Boolean`)
- It shouldn't be possible to edit tokens. Just add and delete. I need to check if editing is problematic security wise.

Feel free to give the implementation a try. I can do the front-end if you want :) It's mostly a copy of the domain section in the settings. Add dialog + delete/edit dialog.

**Comment by BetaHuhn** [comment]
Sure, I will try to implement it on the backend this week!

**Comment by electerious** [comment]
You can give permanent tokens a try in the develop branch. Please let me know if it works!

I had to adjust the implementation, because it was easier to store permanent tokens in a dedicated schema. This way you can create new permanent tokes in the UI without entering your username and password. It also reduces the amount of optional GraphQL parameters which is always a good thing for me. Updating permanent tokens is now also possible.

**Comment by BetaHuhn** [comment]
I just tried it on the develop branch and everything seems to work. Thanks for your work! 

When are you planning on releasing this?

**Comment by electerious** [comment]
Should be ready soon 😊

**Comment by electerious** [comment]
Soon is now. It's part of Ackee v2.2 🎉

**Comment by BetaHuhn** [comment]
Awesome!

I also just released ackee-report [v0.5.0](https://github.com/BetaHuhn/ackee-report/releases/tag/v0.5.0) which adds support for permanent tokens 👍
