### ISSUE TITLE
Ackee on Netlify doesn't shows devices, systems, browsers, languages

### ISSUE THREAD

**Issue by kaknut** [electerious/Ackee#182]
Ackee, when hosted on Netlify, doesn't show devices, systems, browsers, languages. Everything else works fine.

![image](https://user-images.githubusercontent.com/33004850/97875365-494fa180-1d40-11eb-9d97-006812429446.png)

**Comment by electerious** [comment]
It's a bit hidden and the UI does a bad job explaining it, but you need to enable the tracking of personal data in `ackee-tracker`. It's disabled by default because of privacy. Make sure to ask the user for permission before turning this option on.

More:
https://github.com/electerious/ackee-tracker#-options
https://github.com/electerious/Ackee/blob/master/docs/Anonymization.md#personal-data
