### ISSUE TITLE
Add environment variable like ACKEE_TRACKER for enabling detailed by default

### ISSUE THREAD

**Issue by gempain** [electerious/Ackee#186]
**🐣 Is your feature request related to a problem? Please describe.**

The embed code for domains can be customized with the `ACKEE_TRACKER` variable which changes the name of the tracker file. That's a really nice feature. I'd like to see something similar for setting `options.detailed` to true globally.

**💡 Describe the solution you'd like**

Have an `ACKEE_TRACKER_OPTIONS_DETAILED` variable that updates the embed code to:

```
<script ... data-ackee-opts='{ "detailed": true }'></script>
```

To be honest, you could also add one for each options. For example, `ACKEE_TRACKER_OPTIONS_IGNORE_LOCALHOST`:

```
<script ... data-ackee-opts='{ "ignoreLocalhost": true }'></script>
```

PS: is there a way to reach out to you regarding other matters than Ackee ? Tried Linkedin but no luck.

**Comment by electerious** [comment]
The main reason for this is that the script doesn't know if it should send the detailed data or not. We could include the data all the time and simply throw it away when `ACKEE_TRACKER_OPTIONS_DETAILED` is turned off, but that might be problematic privacy-wise. 

Another reason why this option is set client-side is because a user needs to agree that you collect this type of data. It's therefore important that this option is different from domain to domain and from user to user.

**Comment by gempain** [comment]
Enabling this option by default at the client side and ignoring it on the server side would neither be privacy-friendly nor efficient, and is not what I asked for. Having this option enabled by default would also make no-sense privacy-wise. Perhaps another solution would be to add a checkbox below the embed code that allows customizing the snippet before copying it ?

![Screen Shot 2020-11-09 at 10 25 43](https://user-images.githubusercontent.com/13135149/98523540-54da2580-2276-11eb-97d9-97f2b75725fd.png)

That aside, I take time to open issues ([#157](https://github.com/electerious/Ackee/issues/157), [#23](https://github.com/electerious/ackee-tracker/issues/23), [#24](https://github.com/electerious/ackee-tracker/issues/24)) to improve this great project for which I could not thank you enough - though I do agree that I haven't made any PR yet - and greatly appreciate maintainers taking the time to answer thoroughly these, but find it disappointing to have issues closed early without having the opportunity to explain.

If my post-scriptum was inappropriate, I sincerely apologize.

**Comment by electerious** [comment]
I'm still open for a discussion and further comments. Closed doesn't mean we can't talk about it 😊 I just can't keep issues open for further discussions, because it would simply fill my projects with open issues. Which means that after a while I have to manually dig into issues to know if there's an open task or just an unfinished discussion.

Having options in the domain dialog is indeed a nice idea. I just don't know if we need it right now.

`ignoreLocalhost` => I don't think many people are using this option. It's mostly for testing.
`detailed` => Should probably be based on a cookie or localStorage item that is set when the user agrees to be tracked. A checkbox could make it too easy to enable it by default and I don't want that people do that.

I would like to have a select in the domain modal that lets you choose between the different ways to include [ackee-tracker](https://github.com/electerious/ackee-tracker#-usage), but I don't think that would be a help in your case.

**Comment by gempain** [comment]
Thanks for the clarification, I understand better now, and it's absolutely understandable.

I like the idea of configuring this at the site level, it makes a lot of sense. Maybe then we can customize the embed script with the checkbox I mentioned, I don't know, just brainstorming.

**Comment by electerious** [comment]
I've created an issue for the feature I've described, but I don't think that we need a checkbox for the ackee-tracker options right now. As I said, the detailed option shouldn't be simply switched to `true` as it should depend on a cookie, localStorage item or user action. We can't cover those cases in the modal and I don't want an option that allows to copy the code with detailed tracking enabled by default.

https://github.com/electerious/Ackee/issues/189
