### ISSUE TITLE
Unable to set Access-Control-Allow-Credentials Header on Platforms-As-A-Service Deployments

### ISSUE THREAD

**Issue by 4dams** [electerious/Ackee#223]
**🐞 Describe the bug**

When deployed via Vercel, the tracker is unable to send requests to the Ackee API since the `Access-Control-Allow-Credentials` header is missing.

**📚 To Reproduce**

- Deploy Ackee via Vercel
- Add the Tracker to any website

**💡 Expected behavior**

Ackee should be able to communicate with its API.

**🖼️ Screenshots**

![image](https://user-images.githubusercontent.com/28960614/106172684-63f4b380-6193-11eb-8d11-81a06f21c40e.png)

**⚙️ Environment**
 - Installation: Forked Repository deployed on Vercel
 - Ackee version: Latest / 3.0.3 / [`f03ffc8`](https://github.com/electerious/Ackee/commit/f03ffc8f90a535e1560f58a34911efa762b411fb)

**📋 Additional context**

I am pretty sure that the following _"customizations"_ don't have anything to do with this issue, yet I still want to list them here in case they are relevant somehow:

- I am using `{ "detailed": true }` as the `data-ackee-opts`
- `ACKEE_TRACKER` environment variables is set to `a`
- `ACKEE_ALLOW_ORIGIN`  environment variables is set to `*`

Is there any way to get around this, without having to use a reverse proxy, at the moment?

I imagine a way to fix this could be allowing the users to set their own custom headers through environment variables. For example, all environment variables starting with `ACKEE_API_HEADER_` will be added as API response headers.

This could be done by setting multiple environment variables, such as:
- `ACKEE_API_HEADER_CREDENTIALS="Access-Control-Allow-Credentials: true"`
- `ACKEE_API_HEADER_METHODS='Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS" always'`

Or, for a less versatile approach, in addition to the `ACKEE_ALLOW_ORIGIN` environment variable, also add environment variables for `ACKEE_ALLOW_CREDENTIALS`, `ACKEE_ALLOW_METHODS`, and `ACKEE_ALLOW_HEADERS`.

... or the `Access-Control-Allow-Credentials` header could be set to `true` by default.

Sorry if it's me missing out on something here - if not, I would be happy to help creating a PR for this. 👀

**Comment by electerious** [comment]
You can try to disable the `ignoreOwnVisits` option in ackee-tracker. `ignoreOwnVisits` doesn't work with `Access-Control-Allow-Credentials: "*"`, because it's not allowed to send cookies (the login cookie) to a domain that uses a wildcard. The option is enabled by default in v3.

https://github.com/electerious/Ackee/blob/master/CHANGELOG.md#access-control-allow-origin--not-recommended
https://github.com/electerious/ackee-tracker#-options

**Comment by 4dams** [comment]
Thanks for the fast reply!

I will try this out tomorrow when I'm back at my work machine and keep you updated with the results!

**Comment by 4dams** [comment]
Alright, reporting back on this: It actually seems to have done the trick!

Though, I still don't think that this is the best solution for this. 🤔 What exactly is the reason for the `Access-Control-Allow-Credentials`-Header being empty when `ignoreOwnVisits` is set to `true`?

**Comment by Tragio** [comment]
@electerious I'm using Vercel. I fixed this by using the following on `vercel.json`. I would love to have it by default or have some of the solutions of @4dams implemented.

```json
{
  "build": {
    "env": {
      "NODEJS_AWS_HANDLER_NAME": "handler"
    }
  },
  "routes": [
    {
      "src": "/(.*)",
      "headers": {
        "Access-Control-Allow-Credentials": "true"
      }
    }
  ]
}
```

**Comment by electerious** [comment]
> Though, I still don't think that this is the best solution for this. 🤔 What exactly is the reason for the Access-Control-Allow-Credentials-Header being empty when ignoreOwnVisits is set to true?

I don't know why `Access-Control-Allow-Origin` is empty. Maybe some magic in `apollo-server-lambda` that removes the wildcard when sending requests with credentials? It shouldn't be empty: https://github.com/electerious/Ackee/blob/master/src/serverless.js#L21

Browsers will only allow credential requests (as required by `ignoreOwnVisits`) when `Access-Control-Allow-Credentials` isn't a wildcard. We could go around this in Ackee itself by returning the request origin instead of a wildcard. It looks like this is also possible with `apollo-server-lambda`: https://www.apollographql.com/docs/apollo-server/v1/servers/lambda/#modifying-response

A PR for the serverless part is welcome. It would allow `ignoreOwnVisits` even when using a wildcard. I can do the part for the Ackee server :)

**Comment by stolinski** [comment]
Ah, I'm seeing this as well. I'm deploying to Render.com

```
Access to XMLHttpRequest at 'https://analytics.leveluptutorials.com/api' from origin 'https://www.leveluptutorials.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

<img width="672" alt="Screen Shot 2021-02-11 at 9 43 51 AM" src="https://user-images.githubusercontent.com/669383/107668238-b03cfa80-6c4d-11eb-8a97-bd984bf2fbd4.png">


<img width="955" alt="Screen Shot 2021-02-11 at 9 44 31 AM" src="https://user-images.githubusercontent.com/669383/107668313-c64abb00-6c4d-11eb-8adf-172e1ff6a537.png">

**Comment by electerious** [comment]
The bug is indeed fixed by the PR of @elliottsj. It seems that settings `cors: true` reflects the request origin. I previously thought that we need to do that manually.

Will do some testing today. A new version with the fix should follow soon!

**Comment by electerious** [comment]
![Screenshot 2021-02-14 at 15 50 32](https://user-images.githubusercontent.com/499088/107880010-7a617580-6edc-11eb-8567-04e88705ab52.png)

My Vercel installation currently doesn't work because the ts-tiny-invariant module is missing. I don't know why, because it's part of the yarn.lock and in my local node_modules. I will give it another try in a few days…

The fix itself is now part of the develop branch. Feel free to give it a try!

**Comment by elliottsj** [comment]
Thanks @electerious. The module error is pretty strange, and I think it's related to Vercel accidentally omitting that package from the file system. Started a thread here: https://github.com/vercel/vercel/discussions/5846

**Comment by electerious** [comment]
Looks like it has been fixed 😊 I've successfully deployed Ackee to Vercel. A new Ackee version which includes the CORS fix has been published 🚀
