### ISSUE TITLE
baseUrl

### ISSUE THREAD

**Issue by alazhar** [electerious/Ackee#227]
**🐣 Is your feature request related to a problem? Please describe.**

Able to specify baseUrl. So instead of use subdomain like ackee.example.com, We can use example.com/ackee

**💡 Describe the solution you'd like**

add the environment variable to set baseUrl with default /

**❓ Describe alternatives you've considered**

**📋 Additional context**

Add any other context about the feature request here.

**Comment by electerious** [comment]
I don't think that's possible. Ackee creates it's own server which waits for connections on a defined port. That's usually port 80/443 which is reachable via a (sub)domain, but not a directory on the server. It might be possible via a reverse proxy (nginx), but that belongs to the server setup and is nothing I can help with.

**Comment by dodedodo** [comment]
Hey! I'm looking for this feature as well. 

You're right, the BaseURL option must work in conjunction with a reverse proxy. However, a reverse-proxy alone is not enough to change ackee's URL. 

The BaseURL should act as a kind of prefix to the url's that the ackee UI tries to fetch.

**Example:** I configured a reverse proxy to serve `domain.tld/ackee`. The login page shows up just fine, but when I try to login, ackee sends a request to `domain.tld/api`. If the BaseURL is set to `/ackee` this request would instead be directed at `domain.tld/ackee/api`. 

Another option would be to change every URL to a relative one. If ackee requests `./api` instead of `/api`, it would work with whatever base URL. 

Would it be feasible to implement this, @electerious?

I might take a stab at this if I find the time.

**Comment by dodedodo** [comment]
Hey @electerious, can you take a look at my pull request? #317
