### ISSUE TITLE
Server replication

### ISSUE THREAD

**Issue by evilfer** [electerious/Ackee#259]
Hi, is it possible to run multiple ackee servers in parallel to provide a failover mechanism? I'm looking at the documentation but I cannot find anything in the documentation about configuring a replicated ackee server.

One option would be to have multiple ackee servers, each using its own Mongo database. Then we can keep the Mondo databases synchronised using MongoDB mechanisms.

Would the ackee servers have any issue with these databases, if they received updates from other external Mongo databases?

**Comment by electerious** [comment]
The best way to scale Ackee would be to use it in a serverless environment.

I'm not sure what happens when running multiple Ackees or when the database receives updates from other MongoDBs. I've never tested that. I'm also not sure if Ackee is the right tool for you when the tracking is so important that you need a failover mechanism.
