### ISSUE TITLE
Display sizes doesn't respect devicePixelRatio

### ISSUE THREAD

**Issue by slavaGanzin** [electerious/Ackee#294]
Thanks for the ackee. it's awesome!

**🐞 Describe the bug**

When mobile devices screen sizes are tracked their resolution is not multiplied by [devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio)

Ackee show Iphone 12 is 390 x 844, but it's 1170 x 2532.

**📚 To Reproduce**

Get yourself tracked with any mobile phone.

**💡 Expected behavior**

Real screensize are tracked and not viewport sizes.

**⚙️ Environment**
 - Ackee version: [e.g. v3.2]

**Comment by electerious** [comment]
Glad you like Ackee!

`ackee-tracker` uses [`screen.width` and `screen.height` to track the screen size](https://github.com/electerious/ackee-tracker/blob/master/src/scripts/main.js#L86-L87). There's nothing wrong with it, but it might be depending on what you're looking for. I prefer this size, because the real pixels doesn't matter that much when building a website.

But… you can change it if you want 😊 Here's an example using [the `.record` function](https://github.com/electerious/ackee-tracker#%EF%B8%8F-instance-api) with custom attributes.

```js
instance.record('hd11f820-68a1-11e6-8047-79c0c2d9bce0', {
	...ackeeTracker.attributes(true),
	screenWidth: screen.width,
	screenHeight: screen.height,
})
```

This way you can replace `screen.width` and `screen.height` with a custom value that is multiplied by the devicePixelRatio. Hope that helps!
