### ISSUE TITLE
Support passwordless public dashboard

### ISSUE THREAD

**Issue by scaljeri** [electerious/Ackee#355]
**🐣 Is your feature request related to a problem? Please describe.**
On my website I would like to provide (via a link) my visitors a overview of the site's analytics, so I would like to provide the dashboard (only overview) to them.  Right now this seems not possible as you have to provide a username/password

**💡 Describe the solution you'd like**
Provide a public dashboard with some stats, like the the overview dashboard. It would be nice to select which stats you want to show.

I also noticed, that you can enable `demo` mode which results with a prefilled login form

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1078741/231675520-9cde9cbe-20f2-4fae-997c-55ef3644c425.png">

This doesn't make sense. Better would be to remove that login window completely and show the user some kind of readonly dashboard. In my case, I could show that already to my users and would be very helpful!

**Comment by electerious** [comment]
Thanks for the suggestion. I'm closing this issue, because there're already other related issues. See https://github.com/electerious/Ackee/issues/350 and https://github.com/electerious/Ackee/issues/225.

**Comment by electerious** [comment]
> This doesn't make sense. Better would be to remove that login window completely and show the user some kind of readonly dashboard. In my case, I could show that already to my users and would be very helpful!

That's true, but then there would be no way for you to edit your Ackee instance otherwise than turning the demo mode off.  It however sounds like a valid option.

PR suggestion: Replace demo mode with a public mode. Public mode shouldn't show the login (but can do a login in the background to get the token). This would allow to turn public mode off when you want to edit the instance.
