### ISSUE TITLE
Event based tracking

### ISSUE THREAD

**Issue by electerious** [electerious/Ackee#40]
API and UI to allow event based tracking (e.g., button clicks). This is something planned for a later release once all the basics are done (https://github.com/electerious/Ackee/issues/35)

**Comment by electerious** [comment]
Events are still planned. It's something I will focus on after v2: https://github.com/electerious/Ackee/issues/129

**Comment by emschwartz** [comment]
I would find this extremely useful. Is there any way to help with this to speed up the development?

Also, would you envision being able to attach some extra data to events? I'd like to be able to track any front-end errors users might encounter but would need to send the error message along with the event in order to use the information. If you don't think that's in the plan, I'll figure out another way to do it.

**Comment by emschwartz** [comment]
This sounds great! Let me know if you could use any help or a beta tester

**Comment by emschwartz** [comment]
Hey @electerious, any progress on this? Let me know if there's any way for me to help get this feature launched

**Comment by electerious** [comment]
No news for now. I'm currently focusing on the website and stuff around Ackee, but this feature should be the next big thing as soon as I'm back working on Ackee :)

**Comment by BetaHuhn** [comment]
@electerious what's the time frame for this i.e. when will you start working on it? I'd love to help anyway I can, as this is something that would be very useful to me too!

**Comment by electerious** [comment]
The plan right now is:

v2.1 => Final touches, maybe waiting for https://github.com/electerious/Ackee/pull/171
v2.2 => Events
v2.3 => Probably a better dashboard

Might start with events today 👀

**Comment by electerious** [comment]
Update: I'm currently refactoring a few parts of the UI, because the old implementation wasn't good at handling different kinds of widgets in a view. That's something we need as events can be displayed as charts and lists, depending on what the user specified in the settings. The good thing is that it allows me to remove tons of redundant code. The old state management was done with a REST API in mind, not with a GraphQL API. Will continue with the events once this showstopper is resolved.

**Comment by electerious** [comment]
I'm done refactoring the front-end. It's now possible to display multiple types of widgets. I can therefore continue to work on events :)

**Comment by electerious** [comment]
Weekly development update: The events are now in the UI. You can add, edit and delete events and change the display type (more on that once it's done). I'm currently updating ackee-tracker to include the new `.action` and `.updateAction` functions.

**Comment by electerious** [comment]
`ackee-tracker` is ready for events. You can take a sneak peak at the upcoming changelog: https://github.com/electerious/ackee-tracker/blob/feature/events/CHANGELOG.md#unreleased-events

Planning to release this in January as v3 along with some other features.

As always: It's a lot of work and I'm happy about every sponsor: https://github.com/sponsors/electerious

**Comment by electerious** [comment]
v3 is now on the develop branch and ready for testing. It includes the newest beta of ackee-track. You can find everything you need to know in the changelog and in the events documentation:

https://github.com/electerious/Ackee/blob/develop/CHANGELOG.md#unreleased
https://github.com/electerious/Ackee/blob/develop/docs/Events.md

I've also added the ability to show average values (e.g. adding an action with a value of 10 and one with the value of 20 will show 15 in the UI. This could be helpful to measure the performance of sites: https://github.com/electerious/Ackee/issues/207)

Feedback is welcome!

**Comment by BetaHuhn** [comment]
I just tried the new version and its incredible how much faster it feels, especially the installation part!

One thing I noticed is that in the API documentation for events, the example in the [get-events](https://github.com/electerious/Ackee/blob/develop/docs/API.md#get-events) section doesn't work. It is missing the `EventChartType`:

```diff
query getEvents {
	events {
		id
		title
		statistics {
-		        chart(interval: DAILY) {
+                       chart(interval: DAILY, type:TOTAL) {
				id
				count
			}
-                       list(sorting: TOP) {
+		        list(sorting: TOP, type:TOTAL) {
				id
				count
			}
		}
	}
}
```

A few other things:

- In the [documentation](https://github.com/electerious/Ackee/blob/develop/docs/Events.md#event-type) for events it is mentioned that the charts event types can display data for 'Each day, month or year (depending on the chosen interval)'. But in the UI there's no way to change the interval like there's with other metrics.

- I also saw myself constantly having to navigate to the settings page to change the chart type from `total` to `average`. Why not add an option to change how events are displayed right from the events page? To my understanding the API handles every event type the same way, so I see no problem in changing the event type depending on what I want to see right now instead of when creating the event. For some use cases it might be helpful to see both charts and lists, so moving the event type option from the settings page to the events directly would make more sense.

Other than that the new version is awesome. I already have so many ideas for events (might be cool to have a page where we can share them)! Thanks for your hard work @electerious 🙏🎉

**Comment by electerious** [comment]
@BetaHuhn 

Thanks letting me know! I've fixed the docs.

> In the documentation for events it is mentioned that the charts event types can display data for 'Each day, month or year (depending on the chosen interval)'. But in the UI there's no way to change the interval like there's with other metrics.

Totally forgot that. I will add the missing filter for the event page.

> I also saw myself constantly having to navigate to the settings page to change the chart type from total to average. Why not add an option to change how events are displayed right from the events page? To my understanding the API handles every event type the same way, so I see no problem in changing the event type depending on what I want to see right now instead of when creating the event. For some use cases it might be helpful to see both charts and lists, so moving the event type option from the settings page to the events directly would make more sense.

The problem is that it's currently only possible to set filters globally. It's not possible to adjust a filter for a dedicated widget, but that's something I've in mind and should be changed in an upcoming version. It's also the reason why it's not possible to adjust intervals or sorting on the overview and domain pages. It's possible with the API, but I also need to add it to the UI. This also solves the event type dilemma and would allow us to remove them at all (right now they only define what the UI should show).

**Comment by BetaHuhn** [comment]
> GitHub can run scripts in a defined interval via GitHub actions. It would be possible to send reports to Ackee (e.g. GitHub stats, Twitter or Instagram followers, website response times (ping)).

That's a great idea! I will definitely try this when v3 is out.

I had the idea to track uncaught JavaScript errors which are thrown. Using `window.onerror` you could catch any error that occurs on a page and send the error message to Ackee as an event.

**Comment by electerious** [comment]
It's live ✅

I guess there're still things we can improve. Feedback and suggestions are always welcome. Either in new issues or in the community chat: https://gitter.im/electerious-Ackee/community
