### ISSUE TITLE
Add an option for K-anonymity of URLs

### ISSUE THREAD

**Issue by gcampax** [electerious/Ackee#76]
Ackee by default tracks raw, unnormalized URLs of page visits. This is very useful, but it also means that URLs that are unique (for example URLs that contain OAuth codes or other secrets) are also displayed to the Ackee admin. This unfortunately defeats anonymization, and is awful for security.
It would be very useful to have an option to hide all URLs that have not been visited at least by K distinct users, and discard such records at the end of the day.
By default, K should probably be 2, to omit all truly unique URLs.

(Alternatively, Ackee could remove the query string from the URL, and that would solve 90% of the above problem, but eg. search terms or marketing campaigns would not be trackable.)

**Comment by electerious** [comment]
We would need some kind of extension that would allow users to write custom rules as I don't think we can find defaults that work for everyone. It might be better to block those URLs instead of just hiding them.

My first idea: An env variable that lets you specify Regex patterns to block. Ackee will check those before writing them to the database. This however won't allow you to just remove parts of a URL.

> (Alternatively, Ackee could remove the query string from the URL, and that would solve 90% of the above problem, but eg. search terms or marketing campaigns would not be trackable.)

Ackee already applies [small adjustments to URLs](https://github.com/electerious/Ackee/blob/master/src/utils/normalizeUrl.js) before writing them to the database. I can't do too much by default as queries are relevant for some users. It's also possible to build the routing of a webapp via queries for example.

Any other ideas? What do you think about Regex patterns?

**Comment by emschwartz** [comment]
I also have a use case where I don't want to track the full URLs. I opted to modify the URL before it's sent to the server by `ackeeTracker`:

```js
const url = new URL(window.location.href)
url.hash = ''
tracker.record({
    siteLocation: url.toString()
})
```

@gcampax would something like that work for your use case?

**Comment by gcampax** [comment]
Yeah I think the problem is that, as @electerious notes, queries are sometimes relevant and sometimes not. Often, the URL path itself can be sensitive, if it contains say the ID or hash of a document (think Google Doc like link). So none of these solutions would be complete.
I think removing all URLs that have not been seen >= K times (for a configurable K) is a much better approach, and it has the advantage of being an easy-to-defend standard in protecting privacy.

**Comment by electerious** [comment]
I don't think that there's a good way to build an option that works for all users. I would suggest to modify the URL before tracking the visit with `ackee-tracker`. It would be great if someone could add a page to the `docs/` that shows how to do so (with examples).

Here's an example: https://github.com/electerious/Ackee/issues/113#issuecomment-633971352

Would be helpful for #114, #113 and this issue.

**Comment by gcampax** [comment]
Ok, I think it's clear you're not interested in adding this feature. That is fine, and I think the workarounds you suggested are acceptable. Thank you for the all the help, and for this project in this first place. I'm going to close this issue.

**Comment by electerious** [comment]
I've created a new issue. Would be cool if someone could write a documentation for this workaround: https://github.com/electerious/Ackee/issues/163
