### ISSUE TITLE
Option to change the order domains are displayed

### ISSUE THREAD

**Issue by BetaHuhn** [electerious/Ackee#90]
Hello! Thank you for your awesome work, this is exactly what i was looking for.

As I intend to use this with multiple domains, it would be nice to change in what order domains are displayed. Currently they are displayed in alphabetical order, so an option to reverse that order or sort by most Views would be helpful.

**Comment by electerious** [comment]
It's currently not planned to add a custom sorting for domains. It always adds a lot of complexity to the code.

I might take a look at it in the future when there's a higher interested in the feature!

**Comment by BetaHuhn** [comment]
Okay I understand.

I just went through the code structure of Ackee because I was curious how Ackee works. I noticed that it uses React for the Frontend and Micro as the http server? I'm just getting started with React and have previously only worked with Node JS and a static frontend so the structure seems wierd to me. I always read that when you use React you build it and then just use the static files and a sperate app for the backend. But here it seems that everything is in one app. The routes, the backend logic and the react frontend.

Could you maybe explain the structure of Ackee? Thanks!

**Comment by electerious** [comment]
Sure :)

- The front-end and back-end of Ackee are in one repository. This makes it easy to share code between both because everything is JavaScript anyway.
- Most of the front-end code is located in src/ui. All those files are uncompiled. There's no compiled file in the repository.
- When you visit `/index.js` or `/index.css` Ackee will run the compiler and return the final files for the page. This happens here: https://github.com/electerious/Ackee/blob/master/src/routes/ui.js
- Ackee will build and cache the front-end JS and CSS when you start the server. In the development mode however (When you start the server with `yarn dev`) the files won't be cached and it will compile everything each time you request `/index.js` or `/index.css`. This makes development easier.
- Some functions (`src/utils`) are used both on the back-end and front-end.

I hope that helps. Let me know if you have more questions :)

**Comment by BetaHuhn** [comment]
Thanks! Now I understand it a bit better. But still way to advanced for me. Guess I need to learn more about basic react and stuff :D
